name: "archlinux package builder"
description: "I build packages"
inputs:
  action:
    description: 'build or package'
    required: true
    default: 'build'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - "--${{ inputs.action }}"
