name: "archlinux package builder"
description: "I build packages"
inputs:
  action:
    description: 'build or package'
    required: true
runs:
  using: 'docker'
  image: 'docker://ashleyis/aurei-builder:latest'
  args:
    - "--${{ inputs.action }}"
